[connection]
endpoint = "http://pc:8882"
local_fallback = true

[sources]
include = ["src/**", "Cargo.toml", "Cargo.lock"]
exclude = []

[artifacts]
include = ["src/**", "Cargo.toml", "target/release/gsd"]
exclude = []

[request]
timeout_sec = 900

[workspace]
reuse = true
id = "gsd"
create = true
ttl_sec = 0

[output]
stdout_max_lines = 10
stderr_max_lines = 10
stdout_tail_lines = 10
stderr_tail_lines = 10
